XFAIL macos

diff --git a/.github/workflows/gha-yamllint.yml b/.github/workflows/gha-yamllint.yml
--- a/.github/workflows/gha-yamllint.yml
+++ b/.github/workflows/gha-yamllint.yml
@@ -36,32 +36,27 @@ jobs:
 
           if [ "${{ matrix.os }}" == "windows" ] ; then
             if yamllint greek.yml ; then
-              echo "XFAIL: ('English_United States', '1252') cp1252"
-            else
               echo "XPASS: windows locales"
               exit 10
+            else
+              echo "XFAIL: ('English_United States', '1252') cp1252"
             fi
           else
             yamllint greek.yml
             if [ "${{ matrix.os }}" == "ubuntu" ] ; then
               sudo localedef -f CP1251 -i ru_RU ru_RU.CP1251
             fi
-            echo "locale -a"
-            locale -a
-            echo "locale"
-            locale
-            echo "env"
-            env
             export LANG=ru_RU.CP1251
-            echo "locale 2"
+            export LC_ALL=ru_RU.CP1251
             locale
 
             python -c "import locale; \
                        print(locale.getlocale(), \
                              locale.getpreferredencoding())"
             if yamllint greek.yml ; then
-              echo "XFAIL: ru_RU.CP1251"
-            else
               echo "XPASS: ru_RU.CP1251"
+              exit 20
+            else
+              echo "XFAIL: ru_RU.CP1251"
             fi
           fi
